### ISSUE TITLE
不建议重复造轮子以及一点建议

### ISSUE THREAD

**Issue by zwc456baby** [arloor/socks5#4]
类似的伪装已经有 ss，ssr，v2ray 等等等。

其实我有一个自认为很好的建议，

将流伪装成 rtsp 等视频流，rtsp 的特点是：加密、udp tcp 均支持
像现在直播类的app就是基于视频流的
或者音频流 aac 等
其实我也是希望 v2ray 开发类似的基于 视频流 或者音频流的伪装的

**Comment by arloor** [comment]
如果真的觉得rtsp牛逼，就请造轮子。
如果觉得自己造轮子没意义，你就用ss ssr v2ray brook吧。
何必说rtsp来混淆好。

有的人总是停留在想法，却不去做，还嗤笑做的人并美其名曰“不建议”

**Comment by zwc456baby** [comment]
劳资提个建议，全程没有一句不友善， 你奶奶出门买菜必涨价，没点素质

**Comment by zwc456baby** [comment]
开源项目，提出建议，你不接受，觉得建议不好，就关了讨论区。阴阳怪气的说别人，我觉得你也就这样了

**Comment by arloor** [comment]
### 被删掉的评论：

![image](https://user-images.githubusercontent.com/21768987/67761550-76f37200-fa7e-11e9-8494-73285306b277.png)

**Comment by zwc456baby** [comment]
建议你添加先后顺序，谁先出言不逊的

**Comment by arloor** [comment]
你的建议好多啊

**Comment by zwc456baby** [comment]
每天多的是人向微信，qq提各种意见，不接受的多了去了，倒是第一次见你这样的，冷嘲热讽

**Comment by arloor** [comment]
你话真的是多，这issue我不关，留给你关

**Comment by zwc456baby** [comment]
玩泥巴还有人不建议，我话多挡你家门了？

**Comment by LoveItachi** [comment]
我的服务端 和客户端启动后没有任何反应呀 能不能帮忙看下哦？

**Comment by arloor** [comment]
1. 新开issue啊，别在这个无法描述的issue下面说。
2. 如果要排障，请自行提供有效信息，否则我没办法帮到你
